### ISSUE TITLE
Be more flexible with data that is not declared in a schema

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables#58]
After talking with @davidread, a use case arose where we'd like to process data files that have additional fields that are not declared in the JSON Table Schema for that data file.

Options for this scenario:

1. Ignore those extra fields (only validate against the ones in the schema)
2. Infer and validate those extra fields, and give feedback to user about them

**Comment by davidread** [comment]
e.g. spend data sees quite commonly columns included, such as 'supplier post code', which are helpful to users, but aren't part of the schema. Good Tables should not whinge about these. Although it might raise the question whether these are genuinely bonus columns or misspelt optional columns.

**Comment by davidread** [comment]
Here's a CSV we wrote a schema for:
http://data.gov.uk/dataset/clinical-commissioning-group-sites/resource/26370f4a-aa24-4a09-a76d-a2de5466b500
The problem is there duff columns like 'COL18', 'COL19' etc which it seems pointless to mention in the schema. Yet we have to because JSON table schema says:

> fields is an ordered list of field descriptors one for each field (column) in the table

This is the resulting schema: https://raw.githubusercontent.com/datagovuk/health-schemas/add-missing-blank-columns/eccgsite.json

**Comment by pwalsh** [comment]
FIXED
